algoritmo "Interagir_com_Usuario"
var
   nome: caractere
inicio
      escreval("______________________")
      escreval("ROBOR THOR")
      escreval("______________________")
      
      //Entrada de dados:
      escreva("Olá, Como Você se Chama? ")
      leia(nome)
      escreval("------------------------------------------")
      escreval("Oii! ", nome, " Muito Prazer Em Te Conhecer!!!")
      
fimalgoritmo
